// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXB3oMLlHP5TkY5xq8Kg0kPS1TgodZIMo',
    appId: '1:404647340531:web:9c6257b8c92436dad40a86',
    messagingSenderId: '404647340531',
    projectId: 'dmstride5',
    authDomain: 'dmstride5.firebaseapp.com',
    storageBucket: 'dmstride5.firebasestorage.app',
    measurementId: 'G-QMLB0F0M7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiyyXINqjoBn1EnW5iNoKe96xgRRHRR1o',
    appId: '1:404647340531:android:21b7abf0de210704d40a86',
    messagingSenderId: '404647340531',
    projectId: 'dmstride5',
    storageBucket: 'dmstride5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqW8B_qU2JsBU_-EN1iozyDjlot3vrNrE',
    appId: '1:404647340531:ios:0be872fa98efd236d40a86',
    messagingSenderId: '404647340531',
    projectId: 'dmstride5',
    storageBucket: 'dmstride5.firebasestorage.app',
    iosBundleId: 'com.example.dmstridePrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqW8B_qU2JsBU_-EN1iozyDjlot3vrNrE',
    appId: '1:404647340531:ios:0be872fa98efd236d40a86',
    messagingSenderId: '404647340531',
    projectId: 'dmstride5',
    storageBucket: 'dmstride5.firebasestorage.app',
    iosBundleId: 'com.example.dmstridePrueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXB3oMLlHP5TkY5xq8Kg0kPS1TgodZIMo',
    appId: '1:404647340531:web:0e8bafc664ebfebbd40a86',
    messagingSenderId: '404647340531',
    projectId: 'dmstride5',
    authDomain: 'dmstride5.firebaseapp.com',
    storageBucket: 'dmstride5.firebasestorage.app',
    measurementId: 'G-9RNFRWEE2G',
  );
}
